version: "3.9"

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: newuser
      POSTGRES_DB: db_company_management_system_api
    ports:
      - "5432:5432"

  api:
    build: .
    command: sh -c "cd ./company_management_system_api && python manage.py migrate && python manage.py runserver '0.0.0.0:8001'"
    env_file: .env
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    depends_on:
      - db

  celery:
    restart: on-failure
    command:  sh -c "cd ./company_management_system_api && celery -A company_management_system_api worker -B"
    volumes:
      - .:/app
    env_file: .env
    build:
      context: .
    depends_on:
      - db
      - redis

  redis:
    image: redis
    command: redis-server
    ports:
      - "6379:6379"

  flower:
    build: .
    ports:
      - 5555:5555
    command: sh -c "cd ./company_management_system_api && celery -A company_management_system_api flower"
    env_file: .env
    depends_on:
      - redis
      - celery

  adminer:
    image: library/adminer:latest
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres_data: