# Generated by Django 4.1.2 on 2022-10-31 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_code_user_code_expiration_date_user_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='verified',
            new_name='is_verified',
        ),
    ]
