# Generated by Django 4.1.2 on 2022-11-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_verificationcode_remove_user_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AddField(
            model_name='office',
            name='vehicle_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
